[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :1 -screen 0 1280x720x24
autostart=true
autorestart=true

[program:chromium]
command=chromium --no-sandbox --display=:1 --start-maximized --disable-infobars --kiosk "https://www.youtube.com"
environment=DISPLAY=":1"
autostart=true
autorestart=true

[program:x11vnc]
command=x11vnc -display :1 -nopw -listen 0.0.0.0 -xkb -forever
autostart=true
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc 8080 localhost:5900
autostart=true
autorestart=true
